# Generated by Django 5.2.17 on 2026-10-03 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payload",
                    models.JSONField(
                        help_text="ExtractionPayload (см. services/schemas.py)"
                    ),
                ),
                ("conclusion", models.TextField(blank=True)),
                (
                    "summary_for_patient",
                    models.TextField(
                        blank=True, help_text="Нейтральная выжимка без диагноза"
                    ),
                ),
                ("engine", models.CharField(max_length=64)),
                ("dictionary_version", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FindingDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "study_types",
                    models.JSONField(
                        blank=True, default=list, help_text="Пусто = любые исследования"
                    ),
                ),
                (
                    "patterns",
                    models.JSONField(
                        default=list,
                        help_text="Регулярные выражения (синонимы, сокращения)",
                    ),
                ),
                ("exclude_patterns", models.JSONField(blank=True, default=list)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("routine", "Плановая"),
                            ("urgent", "Срочная"),
                            ("emergency", "Экстренная (только эскалация персоналу)"),
                        ],
                        default="routine",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Выполняется"),
                            ("done", "Готово"),
                            ("failed", "Ошибка"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=64)),
                (
                    "engine",
                    models.CharField(
                        blank=True,
                        help_text="rules / llm:<provider> / hybrid",
                        max_length=64,
                    ),
                ),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialtyAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialty_code", models.SlugField(max_length=64)),
                ("pattern", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("evidence_quote", models.TextField()),
                ("span_start", models.IntegerField(blank=True, null=True)),
                ("span_end", models.IntegerField(blank=True, null=True)),
                (
                    "negated",
                    models.BooleanField(
                        default=False, help_text="Упомянуто с отрицанием — не триггер"
                    ),
                ),
                (
                    "uncertain",
                    models.BooleanField(
                        default=False, help_text="«?», «нельзя исключить», «по типу»"
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(default=1.0)),
                ("severity", models.CharField(default="routine", max_length=16)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="processing.extractionresult",
                    ),
                ),
            ],
            options={
                "ordering": ["span_start"],
            },
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result",
                to="processing.processingjob",
            ),
        ),
        migrations.CreateModel(
            name="StudyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_id", models.UUIDField(db_index=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID протокола в МИС 1С",
                        max_length=128,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("file", models.FileField(blank=True, upload_to="protocols/%Y/%m/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("docx", "Word (.docx)"),
                            ("doc", "Word 97-2003 (.doc)"),
                            ("json", "JSON из МИС"),
                        ],
                        max_length=8,
                    ),
                ),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("raw_text", models.TextField(blank=True)),
                ("study_type", models.CharField(blank=True, max_length=128)),
                ("study_date", models.DateField(blank=True, null=True)),
                ("performed_by", models.CharField(blank=True, max_length=255)),
                ("location_code", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Загружен"),
                            ("processing", "В обработке"),
                            ("processed", "Обработан"),
                            ("failed", "Ошибка"),
                            ("superseded", "Заменён новой версией"),
                            ("annulled", "Аннулирован"),
                        ],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("external_id", "version"),
                        name="uniq_protocol_version",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="processingjob",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="processing.studydocument",
            ),
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="processing.studydocument",
            ),
        ),
    ]
