# Generated by Django 5.2.17 on 2026-10-03 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttentionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("finding_code", models.CharField(db_index=True, max_length=64)),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"attr": "size_mm", "op": "gte", "value": 10}]',
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("critical", "Критично"),
                            ("high", "Высокая важность"),
                            ("medium", "Требует внимания"),
                            ("low", "Незначительные изменения"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Пояснение врачу; {value} — значение атрибута",
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Основание (клинические рекомендации, приказ)",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["finding_code", "code"],
            },
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="annotation_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Итог разметки важности и отчёт контроля достоверности ИИ",
            ),
        ),
        migrations.CreateModel(
            name="ProtocolSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        help_text="Исходный порядок в протоколе"
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Место в ранжировании (1 — самое важное)"
                    ),
                ),
                ("section", models.CharField(max_length=16)),
                ("organ", models.CharField(blank=True, max_length=128)),
                ("text", models.TextField()),
                ("span_start", models.PositiveIntegerField()),
                ("span_end", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=24)),
                ("level", models.CharField(db_index=True, max_length=16)),
                ("score", models.FloatField(default=0)),
                ("finding_codes", models.JSONField(blank=True, default=list)),
                ("signs", models.JSONField(blank=True, default=list)),
                ("negated_codes", models.JSONField(blank=True, default=list)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "attention",
                    models.JSONField(
                        blank=True, default=list, help_text="На что обратить внимание"
                    ),
                ),
                ("uncertain", models.BooleanField(default=False)),
                (
                    "linked_to",
                    models.PositiveIntegerField(
                        blank=True, help_text="seq пункта заключения", null=True
                    ),
                ),
                ("link_reason", models.CharField(blank=True, max_length=255)),
                ("not_in_conclusion", models.BooleanField(default=False)),
                (
                    "sources",
                    models.JSONField(blank=True, default=list, help_text="rules / llm"),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="processing.extractionresult",
                    ),
                ),
            ],
            options={
                "ordering": ["result", "seq"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("result", "seq"), name="uniq_segment_seq"
                    )
                ],
            },
        ),
    ]
