# Generated by Django 5.2.17 on 2026-10-04 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0002_annotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.CharField(
                        help_text="Логин врача / координатора",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ключи по порядку: "gallstones", "sign:cyst", "hl:uncertain"',
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Загрузка в кабинете"),
                            ("zip", "Zip-архив"),
                            ("folder", "Папка-наблюдатель"),
                            ("browser_folder", "Папка на компьютере координатора"),
                            ("api", "API МИС"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("location_code", models.CharField(blank=True, max_length=64)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("files_total", models.PositiveIntegerField(default=0)),
                ("accepted", models.PositiveIntegerField(default=0)),
                ("duplicates", models.PositiveIntegerField(default=0)),
                (
                    "rejected",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"file": "...", "error": "..."}]',
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="attentionrule",
            name="level",
        ),
        migrations.RemoveField(
            model_name="protocolsegment",
            name="attention",
        ),
        migrations.RemoveField(
            model_name="protocolsegment",
            name="level",
        ),
        migrations.RemoveField(
            model_name="protocolsegment",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="protocolsegment",
            name="score",
        ),
        migrations.AddField(
            model_name="findingdefinition",
            name="patient_explanation",
            field=models.TextField(
                blank=True,
                help_text="Что это значит простыми словами (2–3 предложения)",
            ),
        ),
        migrations.AddField(
            model_name="findingdefinition",
            name="patient_title",
            field=models.CharField(
                blank=True, help_text="Как назвать находку пациенту", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="protocolsegment",
            name="emergency",
            field=models.BooleanField(
                default=False,
                help_text="Экстренная находка: флаг безопасности, не уровень",
            ),
        ),
        migrations.AddField(
            model_name="protocolsegment",
            name="highlights",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Причины подсветки: [{"type": "size", "text": "..."}]',
            ),
        ),
        migrations.AddField(
            model_name="studydocument",
            name="card_number",
            field=models.CharField(
                blank=True,
                help_text="Номер амбулаторной карты из протокола или имени файла",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="studydocument",
            name="identity",
            field=models.CharField(
                choices=[
                    ("pending", "Пациент ещё не определён"),
                    ("matched", "Пациент определён по номеру карты"),
                    ("manual", "Пациент выбран при загрузке"),
                    ("unmatched", "Пациент не определён (обезличенная карточка)"),
                    ("confirmed", "Пациент подтверждён координатором"),
                ],
                default="manual",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="studydocument",
            name="patient_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="studydocument",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="processing.uploadbatch",
            ),
        ),
        migrations.CreateModel(
            name="SegmentPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seq", models.PositiveIntegerField()),
                ("owner", models.CharField(max_length=150)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="processing.studydocument",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "seq", "owner"), name="uniq_segment_pin"
                    )
                ],
            },
        ),
    ]
