# Generated by Django 5.2.17 on 2026-10-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0003_highlights_batches_focus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadbatch",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Загрузка вручную"),
                    ("zip", "Zip-архив"),
                    ("folder", "Папка-наблюдатель"),
                    ("browser_folder", "Папка на компьютере координатора"),
                    ("api", "API МИС"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
    ]
