# Generated by Django 5.2.17 on 2026-10-04 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0004_batch_source_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Идёт прогон"),
                            ("done", "Готово"),
                            ("failed", "Прогон прерван"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("files_total", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                (
                    "rejected",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"file": "...", "error": "..."}] — не вошли в прогон',
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"файл": ["код правила", ...]} — ожидаемые триггеры',
                    ),
                ),
                ("rows", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
