# Generated by Django 5.2.17 on 2026-10-04 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0005_quality_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionresult",
            name="advice_meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Статус советов ИИ-агента по маршрутизации: режим, модель, ошибка",
            ),
        ),
        migrations.AddField(
            model_name="extractionresult",
            name="analysis",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Маркеры, перекрытия и триггеры с позициями и уверенностью (services/markers.py)",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="rule_id",
            field=models.CharField(
                blank=True,
                help_text="Правило, нашедшее находку: «dictionary:gallstones@v1#2», «scale:birads»",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="RoutingAdvice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seq", models.PositiveSmallIntegerField(default=1)),
                ("text", models.TextField(help_text="Совет: что сделать")),
                ("rationale", models.TextField(help_text="Обоснование: почему")),
                (
                    "evidence_quote",
                    models.TextField(
                        blank=True,
                        help_text="Дословная цитата протокола, на которую опирается совет",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.5,
                        help_text="Уверенность модели (0–1), как её вернула модель",
                    ),
                ),
                ("target_route_code", models.CharField(blank=True, max_length=64)),
                ("target_route_title", models.CharField(blank=True, max_length=255)),
                ("target_specialty_code", models.CharField(blank=True, max_length=64)),
                (
                    "target_executor",
                    models.CharField(
                        blank=True,
                        help_text="Кому адресован: врач, подразделение",
                        max_length=255,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("qwen", "Qwen через LangChain"),
                            ("demo", "Демо-режим без модели"),
                        ],
                        max_length=16,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=128)),
                ("prompt_version", models.CharField(blank=True, max_length=64)),
                (
                    "grounding",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Проверки совета: цитата есть в тексте, маршрут и специальность из справочника",
                    ),
                ),
                (
                    "matches_matrix",
                    models.BooleanField(
                        default=False,
                        help_text="Совпадает с маршрутом, который построила матрица",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_advice",
                        to="processing.studydocument",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_advice",
                        to="processing.extractionresult",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "seq"],
            },
        ),
    ]
