# Generated by Django 5.2.17 on 2026-10-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0006_analysis_advice"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="source",
            field=models.CharField(
                blank=True,
                default="rules",
                help_text="Кто нашёл: rules — словарь, llm — только ИИ-агент, both — словарь и ИИ",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="protocolsegment",
            name="llm_labels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Что во фрагменте нашёл ИИ-агент: [{"quote", "codes", "kind", "highlight"}]',
            ),
        ),
    ]
