# Generated by Django 5.2.17 on 2026-10-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0007_hybrid_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="llm_status",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="timings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="worker",
            field=models.CharField(
                blank=True, help_text="thread:<pid> / celery:<hostname>", max_length=64
            ),
        ),
    ]
