# Generated by Django 5.2.17 on 2026-10-03 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicLocation",
            fields=[
                (
                    "code",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="«Текстильщики», «Сенежская», «Онлайн»",
                        max_length=255,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("is_online", models.BooleanField(default=False)),
                ("has_hospital", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "code",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "title_genitive",
                    models.CharField(
                        blank=True,
                        help_text="«к гинекологу», «гинеколога»",
                        max_length=255,
                    ),
                ),
                ("is_surgical", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "surgical_profiles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Профили, которые реально ведёт врач: hysteroscopy, cholecystectomy ...",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="doctors", to="doctors.cliniclocation"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        related_name="doctors", to="doctors.specialty"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField()),
                (
                    "format",
                    models.CharField(
                        choices=[("offline", "Очно"), ("online", "Онлайн")],
                        default="offline",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Свободен"),
                            ("held", "Удержан (идёт запись)"),
                            ("booked", "Занят"),
                            ("blocked", "Недоступен"),
                        ],
                        db_index=True,
                        default="free",
                        max_length=8,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID слота в сервисе расписания",
                        max_length=128,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doctors.cliniclocation",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("route_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("route_step_id", models.UUIDField(blank=True, null=True)),
                ("source_document_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирован"),
                            ("confirmed", "Подтверждён пациентом"),
                            ("cancelled", "Отменён"),
                            ("no_show", "Неявка"),
                            ("completed", "Приём завершён"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                (
                    "booked_via",
                    models.CharField(
                        choices=[
                            ("patient", "Пациент (личный кабинет)"),
                            ("coordinator", "Координатор"),
                            ("auto", "Автоматически системой"),
                            ("doctor", "Врач"),
                        ],
                        default="patient",
                        max_length=12,
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment",
                        to="doctors.scheduleslot",
                    ),
                ),
            ],
            options={
                "ordering": ["slot__starts_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tactic",
                    models.CharField(
                        choices=[
                            ("surgery_indicated", "Оперативное лечение показано"),
                            ("extra_exam", "Требуется дополнительное обследование"),
                            ("observation", "Динамическое наблюдение"),
                            ("surgery_not_indicated", "Операция не показана"),
                            ("patient_refused", "Пациент отказался"),
                            ("other_profile", "Направление в другой профиль"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "agrees_with_ai_route",
                    models.BooleanField(
                        default=True, help_text="Врач согласен с предложенным маршрутом"
                    ),
                ),
                ("disagreement_reason", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome",
                        to="doctors.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="doctors.doctor"
                    ),
                ),
                (
                    "next_specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("consultation", "Консультация"),
                            ("diagnostics", "Обследование"),
                            ("follow_up", "Контрольный визит"),
                            ("surgery", "Операция"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("service_code", models.CharField(blank=True, max_length=64)),
                ("due_in_days", models.PositiveIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doctors.specialty",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="doctors.visitoutcome",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="scheduleslot",
            constraint=models.UniqueConstraint(
                fields=("doctor", "starts_at"), name="uniq_doctor_slot"
            ),
        ),
    ]
