# Generated by Django 5.2.17 on 2026-10-03 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndicationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                (
                    "finding_code",
                    models.CharField(
                        db_index=True,
                        help_text="Код словаря находок, шкалы (birads_category) или признака (sign:thrombus)",
                        max_length=64,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"attr": "birads", "op": "gte", "value": 4}]',
                    ),
                ),
                (
                    "requirement",
                    models.CharField(
                        choices=[
                            ("consultation", "Консультация специалиста"),
                            ("diagnostics", "Обследование"),
                        ],
                        max_length=16,
                    ),
                ),
                ("specialty_code", models.SlugField(blank=True, max_length=64)),
                (
                    "accepted_specialties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Другие специальности, которые тоже закрывают показание",
                    ),
                ),
                (
                    "service_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Регулярное выражение для обследования",
                        max_length=255,
                    ),
                ),
                ("service_title", models.CharField(blank=True, max_length=255)),
                (
                    "max_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Не позже, чем через N дней", null=True
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Критично (немедленно)"),
                            ("major", "Существенно — на обсуждение координатору"),
                            ("minor", "Замечание"),
                        ],
                        default="major",
                        max_length=16,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        blank=True,
                        help_text="Основание: клинические рекомендации, матрица маршрутизации",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["finding_code", "code"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("document_id", models.UUIDField(db_index=True)),
                ("route_id", models.UUIDField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("protocol", "Рекомендации в протоколе исследования"),
                            ("visit", "Назначения врача на приёме"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="ID приёма для проверки назначений",
                        max_length=64,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("sufficient", "Рекомендации достаточны"),
                            ("needs_review", "Есть замечания"),
                            (
                                "insufficient",
                                "Недостаточно — на обсуждение координатору",
                            ),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ожидает решения координатора"),
                            ("resolved", "Решение принято"),
                            ("not_required", "Решение не требуется"),
                            ("cancelled", "Протокол аннулирован/исправлен"),
                        ],
                        db_index=True,
                        default="not_required",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "items",
                    models.JSONField(
                        default=list, help_text="Что рекомендовал врач (нормализовано)"
                    ),
                ),
                (
                    "indications",
                    models.JSONField(
                        default=list,
                        help_text="Показания по матрице с цитатами-основаниями",
                    ),
                ),
                ("rules_version", models.CharField(blank=True, max_length=16)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_id", "source", "source_ref"),
                        name="uniq_audit_per_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            (
                                "missing_consultation",
                                "Не указана консультация специалиста",
                            ),
                            ("missing_diagnostics", "Не указано обследование"),
                            ("late_timing", "Срок позже допустимого"),
                            (
                                "no_recommendations",
                                "Нет рекомендаций при значимых находках",
                            ),
                            ("not_in_conclusion", "Изменение не вынесено в заключение"),
                            ("unsupported", "Рекомендация без основания в протоколе"),
                        ],
                        max_length=24,
                    ),
                ),
                ("severity", models.CharField(max_length=16)),
                ("message", models.TextField()),
                ("finding_code", models.CharField(blank=True, max_length=64)),
                ("evidence_quote", models.TextField(blank=True)),
                ("specialty_code", models.SlugField(blank=True, max_length=64)),
                ("rule_code", models.CharField(blank=True, max_length=64)),
                (
                    "proposed_operation",
                    models.JSONField(
                        blank=True,
                        help_text="Операция для RoutePlanner.apply_correction",
                        null=True,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает решения"),
                            ("accepted", "Принято — маршрут скорректирован"),
                            ("rejected", "Отклонено — рекомендации врача достаточны"),
                            ("not_required", "Решение не требуется"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decision_comment", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="audit.recommendationaudit",
                    ),
                ),
            ],
            options={
                "ordering": ["audit", "created_at"],
            },
        ),
    ]
