# Generated by Django 5.2.17 on 2026-10-03 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EscalationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("ladder", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouteTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_id", models.UUIDField(db_index=True)),
                (
                    "source_document_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "source_external_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("trigger", "По клинически значимой находке"),
                            ("recommendation", "По рекомендации в протоколе"),
                            ("postop", "Послеоперационное наблюдение"),
                            ("observation", "Динамическое наблюдение"),
                        ],
                        default="trigger",
                        max_length=16,
                    ),
                ),
                ("trigger_code", models.SlugField(blank=True, max_length=64)),
                ("rule_version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        help_text="«Полип эндометрия (УЗИ ОМТ от 26.08.2026)»",
                        max_length=500,
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Цитата, атрибуты, уверенность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Маршрут создан"),
                            ("notified", "Пациент уведомлён"),
                            ("booked", "Записан к специалисту"),
                            ("rebooking_required", "Требуется повторная запись"),
                            ("no_show", "Неявка"),
                            ("visit_done", "Приём состоялся"),
                            ("in_diagnostics", "Дообследование"),
                            ("referred_hospitalization", "Направлен на госпитализацию"),
                            ("hospitalization_scheduled", "Госпитализация назначена"),
                            ("hospitalized", "Госпитализирован"),
                            ("surgery_done", "Операция выполнена"),
                            ("discharged", "Выписан"),
                            ("observation", "Динамическое наблюдение"),
                            ("completed", "Маршрут завершён"),
                            (
                                "not_engaged",
                                "Маршрут не реализован / пациент не вовлечён",
                            ),
                            ("declined", "Пациент отказался"),
                            ("seen_elsewhere", "Обратился в другую клинику"),
                            ("cancelled", "Отменён (протокол аннулирован/исправлен)"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=32,
                    ),
                ),
                (
                    "cycle_no",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Номер витка цикла маршрута"
                    ),
                ),
                ("responsible_unit", models.CharField(blank=True, max_length=255)),
                ("location_code", models.CharField(blank=True, max_length=64)),
                ("detected_at", models.DateTimeField()),
                ("target_date", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_reason", models.CharField(blank=True, max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="routing.patientroute",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Консультация специалиста"),
                            ("online_consultation", "Онлайн-консультация"),
                            ("diagnostics", "Обследование"),
                            (
                                "hospitalization_referral",
                                "Направление на госпитализацию",
                            ),
                            ("hospitalization", "Госпитализация"),
                            ("surgery", "Операция"),
                            ("discharge", "Выписка"),
                            ("follow_up", "Контрольный визит"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("specialty_code", models.SlugField(blank=True, max_length=64)),
                ("service_code", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован (ожидает срока)"),
                            ("awaiting_booking", "Ожидает записи"),
                            ("booked", "Записан"),
                            ("done", "Выполнен"),
                            ("missed", "Неявка"),
                            ("cancelled", "Отменён"),
                            ("skipped", "Пропущен (решение врача/координатора)"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rule", "Матрица маршрутизации"),
                            ("ai_recommendation", "Рекомендация из протокола (AI)"),
                            ("doctor", "Назначение врача"),
                            ("coordinator", "Корректировка координатора"),
                            ("system", "Система (МИС)"),
                        ],
                        default="rule",
                        max_length=24,
                    ),
                ),
                (
                    "offset_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Таймер: через сколько дней после предыдущего этапа",
                    ),
                ),
                ("window_days", models.PositiveIntegerField(default=7)),
                ("earliest_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("auto_book", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("appointment_id", models.UUIDField(blank=True, null=True)),
                ("escalation_level", models.PositiveSmallIntegerField(default=0)),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Номер попытки записи (после неявки/отмены)",
                    ),
                ),
                (
                    "outcome",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Тактика врача по итогам этапа",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "escalation_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="routing.escalationpolicy",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="routing.patientroute",
                    ),
                ),
            ],
            options={
                "ordering": ["route", "order"],
            },
        ),
        migrations.CreateModel(
            name="RouteEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(blank=True, max_length=32)),
                (
                    "actor_type",
                    models.CharField(
                        default="system",
                        help_text="system / ai / patient / doctor / coordinator / mis",
                        max_length=24,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=64)),
                (
                    "basis",
                    models.CharField(
                        blank=True,
                        help_text="Основание: правило+версия, событие МИС, решение врача",
                        max_length=500,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="routing.patientroute",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="routing.routestep",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RouteTemplateStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Консультация специалиста"),
                            ("online_consultation", "Онлайн-консультация"),
                            ("diagnostics", "Обследование"),
                            (
                                "hospitalization_referral",
                                "Направление на госпитализацию",
                            ),
                            ("hospitalization", "Госпитализация"),
                            ("surgery", "Операция"),
                            ("discharge", "Выписка"),
                            ("follow_up", "Контрольный визит"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("specialty_code", models.SlugField(blank=True, max_length=64)),
                ("service_code", models.CharField(blank=True, max_length=64)),
                (
                    "offset_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Через сколько дней после предыдущего этапа",
                    ),
                ),
                (
                    "window_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Целевой срок выполнения этапа"
                    ),
                ),
                (
                    "auto_book",
                    models.BooleanField(
                        default=False,
                        help_text="Записать пациента заранее (послеоперационный контроль)",
                    ),
                ),
                (
                    "escalation_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="routing.escalationpolicy",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="routing.routetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "order"],
            },
        ),
        migrations.CreateModel(
            name="TriggerRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                ("finding_code", models.SlugField(max_length=64)),
                ("conditions", models.JSONField(blank=True, default=list)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Меньше — важнее (при нескольких находках)",
                    ),
                ),
                (
                    "route_group",
                    models.SlugField(
                        blank=True,
                        help_text="Клиническое направление: из одного протокола — один маршрут на группу (полип + миома -> один гинекологический маршрут)",
                        max_length=64,
                    ),
                ),
                ("first_specialty_code", models.SlugField(max_length=64)),
                (
                    "potential_route",
                    models.CharField(
                        blank=True,
                        help_text="Подсказка врачу: «Гистероскопия»",
                        max_length=255,
                    ),
                ),
                (
                    "target_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Целевой срок до консультации"
                    ),
                ),
                ("responsible_unit", models.CharField(blank=True, max_length=255)),
                ("is_surgical", models.BooleanField(default=False)),
                (
                    "is_emergency",
                    models.BooleanField(
                        default=False,
                        help_text="Только эскалация персоналу, без сообщений пациенту",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="routing.routetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "code"],
            },
        ),
        migrations.AddField(
            model_name="patientroute",
            name="trigger_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="routing.triggerrule",
            ),
        ),
        migrations.AddConstraint(
            model_name="triggerrule",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="uniq_rule_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="patientroute",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("source_external_id", ""), _negated=True),
                    models.Q(("status", "cancelled"), _negated=True),
                ),
                fields=("patient_id", "source_external_id", "trigger_code"),
                name="uniq_route_per_trigger",
            ),
        ),
    ]
