# Generated by Django 5.2.17 on 2026-10-03 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("lk", "Личный кабинет"),
                            ("push", "Push"),
                            ("sms", "SMS"),
                        ],
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                (
                    "buttons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"action": "book", "label": "Записаться"}]',
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "channel"), name="uniq_template_channel"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_mis_id",
                    models.CharField(
                        help_text="Номер амбулаторной карты в 1С",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Псевдоним / имя для обращения", max_length=255
                    ),
                ),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True, choices=[("F", "Ж"), ("M", "М")], max_length=1
                    ),
                ),
                ("push_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                (
                    "phone_masked",
                    models.CharField(
                        blank=True,
                        help_text="+7 *** ***-12-34 — сам номер хранит МИС",
                        max_length=32,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("route_step_id", models.UUIDField(blank=True, null=True)),
                ("template_code", models.SlugField(max_length=64)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("lk", "Личный кабинет"),
                            ("push", "Push"),
                            ("sms", "SMS"),
                        ],
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("buttons", models.JSONField(blank=True, default=list)),
                (
                    "deep_link",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка сразу на подходящие слоты",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("sent", "Отправлено"),
                            ("read", "Прочитано"),
                            ("failed", "Ошибка"),
                            ("suppressed", "Подавлено (антиспам/маршрут закрыт)"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=255)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_id", models.UUIDField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("book", "Записался"),
                            ("seen_elsewhere", "Уже обратился к врачу"),
                            ("decline", "Не планирую обращаться"),
                            ("callback", "Заказал обратный звонок"),
                            ("confirm", "Подтвердил запись"),
                        ],
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.notification",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("webpush", "Web Push"),
                            ("fcm", "FCM"),
                            ("apns", "APNs"),
                        ],
                        default="webpush",
                        max_length=16,
                    ),
                ),
                ("endpoint", models.TextField()),
                ("keys", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
