# Generated by Django 5.2.17 on 2026-10-04 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="push_enabled",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="sms_enabled",
        ),
        migrations.AddField(
            model_name="patient",
            name="card_hint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Номер карты из протокола, не найденный в МИС",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="hints",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Подсказки для разбора: файлы, типы и даты исследований",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_anonymous",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="large_text",
            field=models.BooleanField(
                default=False, help_text="Крупный шрифт в личном кабинете"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="location_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="patient",
            name="merged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="merged_into",
            field=models.UUIDField(
                blank=True,
                help_text="Пациент, к которому привязаны протоколы",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="placeholder_code",
            field=models.CharField(
                blank=True,
                help_text="ОП-0001 — номер для разбора координатором",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="prefs_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда пациент сам менял каналы (согласие)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="sms_hint_dismissed_at",
            field=models.DateTimeField(
                blank=True, help_text="Пациент скрыл совет включить SMS", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("lk", "Личный кабинет"),
                    ("push", "Push"),
                    ("sms", "SMS"),
                    ("call", "Звонок"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="channel",
            field=models.CharField(
                choices=[
                    ("lk", "Личный кабинет"),
                    ("push", "Push"),
                    ("sms", "SMS"),
                    ("call", "Звонок"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="external_mis_id",
            field=models.CharField(
                blank=True,
                help_text="Номер амбулаторной карты в 1С (пусто у обезличенной карточки)",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_group",
                    models.CharField(
                        choices=[
                            ("results", "Результаты исследований"),
                            ("route", "Следующий шаг маршрута"),
                            ("appointments", "Записи к врачу"),
                            ("reminders", "Напоминания"),
                        ],
                        max_length=16,
                    ),
                ),
                ("push", models.BooleanField(default=True)),
                ("sms", models.BooleanField(default=False)),
                ("call", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "event_group"),
                        name="uniq_patient_event_group",
                    )
                ],
            },
        ),
    ]
