# Generated by Django 5.2.17 on 2026-10-03 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_at", models.DateTimeField(db_index=True)),
                ("metrics", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="RouteFact",
            fields=[
                ("route_id", models.UUIDField(primary_key=True, serialize=False)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(blank=True, max_length=16)),
                (
                    "trigger_code",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("location", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(null=True)),
                ("notified_at", models.DateTimeField(null=True)),
                ("booked_at", models.DateTimeField(null=True)),
                ("visit_at", models.DateTimeField(null=True)),
                ("tactic", models.CharField(blank=True, max_length=32)),
                ("doctor_agreed", models.BooleanField(null=True)),
                ("surgery_recommended_at", models.DateTimeField(null=True)),
                ("hosp_scheduled_at", models.DateTimeField(null=True)),
                ("hospitalized_at", models.DateTimeField(null=True)),
                ("surgery_at", models.DateTimeField(null=True)),
                ("discharged_at", models.DateTimeField(null=True)),
                ("control_visit_at", models.DateTimeField(null=True)),
                ("no_show_count", models.PositiveSmallIntegerField(default=0)),
                ("escalations", models.PositiveSmallIntegerField(default=0)),
                ("closed_at", models.DateTimeField(null=True)),
                ("close_status", models.CharField(blank=True, max_length=32)),
                ("parent_route_id", models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CoordinatorTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("route_step_id", models.UUIDField(blank=True, null=True)),
                ("patient_id", models.UUIDField(db_index=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            (
                                "call_patient",
                                "Позвонить пациенту (5-7 дней без записи)",
                            ),
                            ("callback", "Обратный звонок по заявке пациента"),
                            ("hospitalization_date", "Назначить дату госпитализации"),
                            ("head_escalation", "Эскалация руководителю"),
                            ("book_follow_up", "Записать на контрольный приём"),
                            ("emergency", "Экстренная находка — немедленно связаться"),
                            (
                                "review_route",
                                "Проверить маршрут (расхождение ИИ и врача)",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Критичный"), (2, "Высокий"), (3, "Обычный")],
                        default=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыта"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("script", models.TextField(blank=True, help_text="Скрипт звонка")),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("responsible_unit", models.CharField(blank=True, max_length=255)),
                ("resolution", models.TextField(blank=True)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "priority", "due_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_id", models.UUIDField(db_index=True)),
                ("patient_id", models.UUIDField()),
                ("document_id", models.UUIDField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("doctor_disagreed", "Врач не согласился с маршрутом ИИ"),
                            ("coordinator", "Открыт координатором"),
                            ("patient", "Обращение пациента"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыт"),
                            ("corrected", "Маршрут скорректирован"),
                            ("confirmed", "Маршрут врача подтверждён"),
                            ("ai_error", "Ошибка распознавания (в разметку)"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "ai_markers",
                    models.JSONField(
                        default=list, help_text="Снимок находок ИИ с цитатами"
                    ),
                ),
                (
                    "ai_route",
                    models.JSONField(
                        default=dict, help_text="Маршрут, предложенный матрицей"
                    ),
                ),
                (
                    "doctor_route",
                    models.JSONField(
                        default=dict, help_text="Тактика и назначения врача"
                    ),
                ),
                ("discrepancies", models.JSONField(default=list)),
                ("reason", models.TextField(blank=True)),
                ("resolution_comment", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouteCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_id", models.UUIDField(db_index=True)),
                (
                    "operations",
                    models.JSONField(
                        help_text="Операции для RoutePlanner.apply_correction"
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="coordinator.routereview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
