# Generated by Django 5.2.17 on 2026-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordinator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routereview",
            name="audit_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Проверка рекомендаций (модуль audit)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coordinatortask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("call_patient", "Позвонить пациенту (5-7 дней без записи)"),
                    ("callback", "Обратный звонок по заявке пациента"),
                    ("hospitalization_date", "Назначить дату госпитализации"),
                    ("head_escalation", "Эскалация руководителю"),
                    ("book_follow_up", "Записать на контрольный приём"),
                    ("emergency", "Экстренная находка — немедленно связаться"),
                    ("review_route", "Проверить маршрут (расхождение ИИ и врача)"),
                    (
                        "review_recommendations",
                        "Обсудить рекомендации (возможен пропуск показания)",
                    ),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="routecorrection",
            name="route_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="routereview",
            name="route_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Пусто, если по протоколу ещё нет маршрута (его создаст решение координатора)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="routereview",
            name="source",
            field=models.CharField(
                choices=[
                    ("doctor_disagreed", "Врач не согласился с маршрутом ИИ"),
                    ("coordinator", "Открыт координатором"),
                    ("patient", "Обращение пациента"),
                    (
                        "recommendation_audit",
                        "Проверка рекомендаций: возможен пропуск показания",
                    ),
                ],
                max_length=24,
            ),
        ),
    ]
