# Generated by Django 5.2.17 on 2026-10-04 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordinator", "0002_recommendation_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=64)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Красный — только экстренное"),
                            ("amber", "Янтарный — проверить"),
                            ("green", "Зелёный — в порядке"),
                            ("blue", "Синий — информация"),
                            ("violet", "Фиолетовый"),
                            ("gray", "Серый"),
                        ],
                        default="blue",
                        max_length=8,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_system", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-is_system", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolCase",
            fields=[
                ("document_id", models.UUIDField(primary_key=True, serialize=False)),
                ("patient_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("is_placeholder", models.BooleanField(default=False)),
                ("card_number", models.CharField(blank=True, max_length=64)),
                ("batch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "location",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("study_type", models.CharField(blank=True, max_length=128)),
                ("study_date", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        default="uploaded",
                        help_text="Статус документа в модуле обработки",
                        max_length=16,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "findings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Коды находок (без отрицаний)",
                    ),
                ),
                (
                    "explanation",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Почему так: [{"finding", "quote", "rule"}] — для строки списка',
                    ),
                ),
                ("route_ids", models.JSONField(blank=True, default=list)),
                ("audit_verdict", models.CharField(blank=True, max_length=16)),
                (
                    "reasons",
                    models.JSONField(
                        blank=True, default=list, help_text="Коды системных меток"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("processing", "В обработке"),
                            ("emergency", "Экстренно"),
                            ("failed", "Ошибка обработки"),
                            ("unmatched", "Пациент не определён"),
                            ("needs_review", "Нужна проверка"),
                            ("routed", "Маршрут запущен"),
                            ("no_findings", "Без находок"),
                            ("closed", "Снято с разбора"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                (
                    "uploaded_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="cases", to="coordinator.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
