# Generated by Django 5.2.17 on 2026-10-04 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordinator", "0003_tag_protocolcase"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdviceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        help_text="Кто оценил (логин сотрудника)",
                        max_length=150,
                    ),
                ),
                ("advice_id", models.UUIDField(db_index=True)),
                ("document_id", models.UUIDField(db_index=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("accept", "Принять"),
                            ("reject", "Отклонить"),
                            ("correct", "Скорректировать"),
                        ],
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "corrected_route_code",
                    models.CharField(
                        blank=True,
                        help_text="Маршрут, который предлагает координатор",
                        max_length=64,
                    ),
                ),
                (
                    "advice_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Совет на момент оценки (текст, маршрут, уверенность)",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
